/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.Ignore;

public class LibraryTest {
    @Test
    @Ignore
    public void testSomeLibraryMethod() {
        
    }
}
